# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: ^(poetry.lock|.vscode/)
default_language_version:
  python: python3.11

repos:

  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        types: [python]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.15
    hooks:
    -   id: ruff
        args:
        - --fix
        - --exit-non-zero-on-fix
        - --preview

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
        args: [--unsafe]
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: ['--remove']
      - id: file-contents-sorter
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: name-tests-test
        args: ['--pytest-test-first']
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: pretty-format-json
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: [--install-types, --non-interactive]
        additional_dependencies: [
          pydantic
        ]
        exclude: "(?x)^(
            tests/.*|
            async_casbin_sqlmodel_adapter/adapter.pyi|
          )$"

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.3
    hooks:
      - id: python-safety-dependencies-check
        files: pyproject.toml
