name: Pytest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up Python 3.10
      uses: actions/setup-python@v2.3.2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install -U pip
        pip install poetry
        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest --cov
        poetry run coverage xml
        ls -al
    - name: Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        files: coverage.xml
